### ISSUE TITLE
Create obliquity models/generic time dependent models

### ISSUE THREAD

**Issue by tmcclintock** [Bramson-Planetary-Research-Group/Mars-Troughs#34]
Obliquity could end up being a better predictor of the TMP than solar insolation (or both could end up being important).

The easiest way to do this would be to abstract the current `InsolationAccumulationModel` class into something like a `TimeDependentAccumulationModel` class, that took in any `(times, other)` tuple of arrays where 'other' could be anything (e.g. insolation or obliquity or ...; and strictly speaking the current `InsolationAccumulationModel` could just be renamed and achieve this).  This way we can handle any time-dependent predictor in the same way.

Happy to hear alternatives.

**Comment by klaferr** [comment]
Wouldn’t this require us to change the way we call accumulation model from the trough.py file? Since right now we always feed the accumulation model the insolation as a parameter regardless of which model name is provided to it, so changing it depending on the model name would have to be an additional step added to the trough.py file?

**Comment by tmcclintock** [comment]
Yes, good point. Changing the `Trough` class is unavoidable if we want to explore anything but insolation based models.
